import os
import django

# Configurar el entorno de Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ing_sw_project.settings')
django.setup()

from core.models import Carrera

# Datos de ejemplo
carreras = [
    {
        "NombreUniversidad": "Universidad de Chile",
        "NombreCarrera": "Ingeniería Civil",
        "DescripcionCarrera": "Carrera de ingeniería civil.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Ingeniería",
        "Arancel": 5000000,
        "Matricula": 150000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.uchile.cl/ingenieria-civil"
    },
    {
        "NombreUniversidad": "Pontificia Universidad Católica de Chile",
        "NombreCarrera": "Medicina",
        "DescripcionCarrera": "Carrera de medicina.",
        "SemestresCarrera": 14,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Salud",
        "Arancel": 6000000,
        "Matricula": 200000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.uc.cl/medicina"
    },
    {
        "NombreUniversidad": "Universidad de Concepción",
        "NombreCarrera": "Derecho",
        "DescripcionCarrera": "Carrera de derecho.",
        "SemestresCarrera": 10,
        "RegionCarrera": 8,
        "ComunaCarrera": "Concepción",
        "AreaEstudio": "Ciencias Sociales",
        "Arancel": 4500000,
        "Matricula": 180000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.udec.cl/derecho"
    },
    {
        "NombreUniversidad": "Universidad de Santiago de Chile",
        "NombreCarrera": "Ingeniería Comercial",
        "DescripcionCarrera": "Carrera de ing. comercial.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Administración y Comercio",
        "Arancel": 4700000,
        "Matricula": 130000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.usach.cl/ingenieria-comercial"
    },
    {
        "NombreUniversidad": "Universidad Técnica Federico Santa María",
        "NombreCarrera": "Ingeniería Eléctrica",
        "DescripcionCarrera": "Carrera de ing. eléctrica.",
        "SemestresCarrera": 10,
        "RegionCarrera": 5,
        "ComunaCarrera": "Valparaíso",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4800000,
        "Matricula": 160000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.usm.cl/ingenieria-electrica"
    },
    {
        "NombreUniversidad": "Universidad de Valparaíso",
        "NombreCarrera": "Arquitectura",
        "DescripcionCarrera": "Carrera de arquitectura.",
        "SemestresCarrera": 10,
        "RegionCarrera": 5,
        "ComunaCarrera": "Valparaíso",
        "AreaEstudio": "Arte y Arquitectura",
        "Arancel": 4500000,
        "Matricula": 140000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.uv.cl/arquitectura"
    },
    {
        "NombreUniversidad": "Universidad Austral de Chile",
        "NombreCarrera": "Medicina Veterinaria",
        "DescripcionCarrera": "Carrera de vet. medicina.",
        "SemestresCarrera": 10,
        "RegionCarrera": 14,
        "ComunaCarrera": "Valdivia",
        "AreaEstudio": "Salud",
        "Arancel": 4600000,
        "Matricula": 150000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.uach.cl/medicina-veterinaria"
    },
    {
        "NombreUniversidad": "Universidad de La Frontera",
        "NombreCarrera": "Enfermería",
        "DescripcionCarrera": "Carrera de enfermería.",
        "SemestresCarrera": 10,
        "RegionCarrera": 9,
        "ComunaCarrera": "Temuco",
        "AreaEstudio": "Salud",
        "Arancel": 4400000,
        "Matricula": 120000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.ufro.cl/enfermeria"
    },
    {
        "NombreUniversidad": "Universidad de Antofagasta",
        "NombreCarrera": "Geología",
        "DescripcionCarrera": "Carrera de geología.",
        "SemestresCarrera": 10,
        "RegionCarrera": 2,
        "ComunaCarrera": "Antofagasta",
        "AreaEstudio": "Ciencias",
        "Arancel": 4700000,
        "Matricula": 140000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.uantof.cl/geologia"
    },
    {
        "NombreUniversidad": "Universidad Católica del Norte",
        "NombreCarrera": "Astronomía",
        "DescripcionCarrera": "Carrera de astronomía.",
        "SemestresCarrera": 10,
        "RegionCarrera": 2,
        "ComunaCarrera": "Antofagasta",
        "AreaEstudio": "Ciencias",
        "Arancel": 4900000,
        "Matricula": 150000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.ucn.cl/astronomia"
    },
    {
        "NombreUniversidad": "Universidad de Tarapacá",
        "NombreCarrera": "Psicología",
        "DescripcionCarrera": "Carrera de psicología.",
        "SemestresCarrera": 10,
        "RegionCarrera": 15,
        "ComunaCarrera": "Arica",
        "AreaEstudio": "Ciencias Sociales",
        "Arancel": 4200000,
        "Matricula": 120000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.uta.cl/psicologia"
    },
    {
        "NombreUniversidad": "Universidad de Magallanes",
        "NombreCarrera": "Ingeniería en Recursos Naturales",
        "DescripcionCarrera": "Carrera de ing. recursos.",
        "SemestresCarrera": 10,
        "RegionCarrera": 12,
        "ComunaCarrera": "Punta Arenas",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4600000,
        "Matricula": 140000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.umag.cl/ingenieria-recursos"
    },
    {
        "NombreUniversidad": "Universidad de Talca",
        "NombreCarrera": "Agronomía",
        "DescripcionCarrera": "Carrera de agronomía.",
        "SemestresCarrera": 10,
        "RegionCarrera": 7,
        "ComunaCarrera": "Talca",
        "AreaEstudio": "Ciencias Agrarias",
        "Arancel": 4300000,
        "Matricula": 130000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.utalca.cl/agronomia"
    },
    {
        "NombreUniversidad": "Universidad de Los Lagos",
        "NombreCarrera": "Educación Parvularia",
        "DescripcionCarrera": "Carrera de ed. parvularia.",
        "SemestresCarrera": 8,
        "RegionCarrera": 10,
        "ComunaCarrera": "Osorno",
        "AreaEstudio": "Educación",
        "Arancel": 4100000,
        "Matricula": 110000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.ulagos.cl/educacion-parvularia"
    },
    {
        "NombreUniversidad": "Universidad del Bío-Bío",
        "NombreCarrera": "Diseño Industrial",
        "DescripcionCarrera": "Carrera de diseño ind.",
        "SemestresCarrera": 10,
        "RegionCarrera": 8,
        "ComunaCarrera": "Concepción",
        "AreaEstudio": "Arte y Arquitectura",
        "Arancel": 4400000,
        "Matricula": 130000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.ubiobio.cl/diseno-industrial"
    },
    {
        "NombreUniversidad": "Universidad de Atacama",
        "NombreCarrera": "Minería",
        "DescripcionCarrera": "Carrera de minería.",
        "SemestresCarrera": 10,
        "RegionCarrera": 3,
        "ComunaCarrera": "Copiapó",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4500000,
        "Matricula": 140000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.uda.cl/mineria"
    },
    {
        "NombreUniversidad": "Universidad de La Serena",
        "NombreCarrera": "Ingeniería Mecánica",
        "DescripcionCarrera": "Carrera de ing. mecánica.",
        "SemestresCarrera": 10,
        "RegionCarrera": 4,
        "ComunaCarrera": "La Serena",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4600000,
        "Matricula": 130000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.userena.cl/ingenieria-mecanica"
    },
    {
        "NombreUniversidad": "Universidad de Playa Ancha",
        "NombreCarrera": "Pedagogía en Educación Física",
        "DescripcionCarrera": "Carrera de ed. física.",
        "SemestresCarrera": 8,
        "RegionCarrera": 5,
        "ComunaCarrera": "Valparaíso",
        "AreaEstudio": "Educación",
        "Arancel": 4200000,
        "Matricula": 110000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.upla.cl/educacion-fisica"
    },
    {
        "NombreUniversidad": "Universidad Metropolitana de Ciencias de la Educación",
        "NombreCarrera": "Pedagogía en Inglés",
        "DescripcionCarrera": "Carrera de pedagogía inglés.",
        "SemestresCarrera": 8,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Educación",
        "Arancel": 4300000,
        "Matricula": 120000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.umce.cl/pedagogia-ingles"
    },
    {
        "NombreUniversidad": "Universidad Católica de la Santísima Concepción",
        "NombreCarrera": "Ingeniería Ambiental",
        "DescripcionCarrera": "Carrera de ing. ambiental.",
        "SemestresCarrera": 10,
        "RegionCarrera": 8,
        "ComunaCarrera": "Concepción",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4400000,
        "Matricula": 140000,
        "Gratuidad": True,
        "Regimen": "Diurno",
        "link": "http://www.ucsc.cl/ingenieria-ambiental"
    },
    {
        "NombreUniversidad": "Universidad Adolfo Ibáñez",
        "NombreCarrera": "Ingeniería Comercial",
        "DescripcionCarrera": "Carrera de ing. comercial.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Administración y Comercio",
        "Arancel": 5000000,
        "Matricula": 150000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uai.cl/ingenieria-comercial"
    },
    {
        "NombreUniversidad": "Universidad del Desarrollo",
        "NombreCarrera": "Diseño",
        "DescripcionCarrera": "Carrera de diseño.",
        "SemestresCarrera": 8,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Arte y Arquitectura",
        "Arancel": 4800000,
        "Matricula": 130000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.udd.cl/diseno"
    },
    {
        "NombreUniversidad": "Universidad Finis Terrae",
        "NombreCarrera": "Nutrición y Dietética",
        "DescripcionCarrera": "Carrera de nutrición.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Salud",
        "Arancel": 4500000,
        "Matricula": 120000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uft.cl/nutricion"
    },
    {
        "NombreUniversidad": "Universidad San Sebastián",
        "NombreCarrera": "Odontología",
        "DescripcionCarrera": "Carrera de odontología.",
        "SemestresCarrera": 12,
        "RegionCarrera": 10,
        "ComunaCarrera": "Puerto Montt",
        "AreaEstudio": "Salud",
        "Arancel": 6000000,
        "Matricula": 200000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uss.cl/odontologia"
    },
    {
        "NombreUniversidad": "Universidad Andrés Bello",
        "NombreCarrera": "Fonoaudiología",
        "DescripcionCarrera": "Carrera de fonoaudiología.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Salud",
        "Arancel": 4700000,
        "Matricula": 150000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.unab.cl/fonoaudiologia"
    },
    {
        "NombreUniversidad": "Universidad Autónoma de Chile",
        "NombreCarrera": "Ingeniería Civil Industrial",
        "DescripcionCarrera": "Carrera de ing. industrial.",
        "SemestresCarrera": 10,
        "RegionCarrera": 9,
        "ComunaCarrera": "Temuco",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4900000,
        "Matricula": 140000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uautonoma.cl/ingenieria-industrial"
    },
    {
        "NombreUniversidad": "Universidad Central de Chile",
        "NombreCarrera": "Trabajo Social",
        "DescripcionCarrera": "Carrera de trabajo social.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Ciencias Sociales",
        "Arancel": 4300000,
        "Matricula": 120000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.ucentral.cl/trabajo-social"
    },
    {
        "NombreUniversidad": "Universidad Mayor",
        "NombreCarrera": "Química y Farmacia",
        "DescripcionCarrera": "Carrera de química.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Salud",
        "Arancel": 5000000,
        "Matricula": 150000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.umayor.cl/quimica-farmacia"
    },
    {
        "NombreUniversidad": "Universidad Diego Portales",
        "NombreCarrera": "Ingeniería en Informática",
        "DescripcionCarrera": "Carrera de ing. informática.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4700000,
        "Matricula": 140000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.udp.cl/ingenieria-informatica"
    },
    {
        "NombreUniversidad": "Universidad Bernardo O'Higgins",
        "NombreCarrera": "Derecho",
        "DescripcionCarrera": "Carrera de derecho.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Ciencias Sociales",
        "Arancel": 4500000,
        "Matricula": 130000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.ubo.cl/derecho"
    },
    {
        "NombreUniversidad": "Universidad de Las Américas",
        "NombreCarrera": "Contador Auditor",
        "DescripcionCarrera": "Carrera de contador.",
        "SemestresCarrera": 8,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Administración y Comercio",
        "Arancel": 4400000,
        "Matricula": 120000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.udla.cl/contador-auditor"
    },
    {
        "NombreUniversidad": "Universidad San Sebastián",
        "NombreCarrera": "Kinesiología",
        "DescripcionCarrera": "Carrera de kinesiología.",
        "SemestresCarrera": 10,
        "RegionCarrera": 8,
        "ComunaCarrera": "Concepción",
        "AreaEstudio": "Salud",
        "Arancel": 4600000,
        "Matricula": 140000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uss.cl/kinesiologia"
    },
    {
        "NombreUniversidad": "Universidad Santo Tomás",
        "NombreCarrera": "Fonoaudiología",
        "DescripcionCarrera": "Carrera de fonoaudiología.",
        "SemestresCarrera": 10,
        "RegionCarrera": 8,
        "ComunaCarrera": "Concepción",
        "AreaEstudio": "Salud",
        "Arancel": 4700000,
        "Matricula": 140000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.ust.cl/fonoaudiologia"
    },
    {
        "NombreUniversidad": "Universidad Tecnológica Metropolitana",
        "NombreCarrera": "Diseño Industrial",
        "DescripcionCarrera": "Carrera de diseño industrial.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Arte y Arquitectura",
        "Arancel": 4500000,
        "Matricula": 130000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.utem.cl/diseno-industrial"
    },
    {
        "NombreUniversidad": "Universidad Academia de Humanismo Cristiano",
        "NombreCarrera": "Sociología",
        "DescripcionCarrera": "Carrera de sociología.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Ciencias Sociales",
        "Arancel": 4200000,
        "Matricula": 110000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.academia.cl/sociologia"
    },
    {
        "NombreUniversidad": "Universidad Alberto Hurtado",
        "NombreCarrera": "Ciencias Políticas",
        "DescripcionCarrera": "Carrera de ciencias políticas.",
        "SemestresCarrera": 10,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Ciencias Sociales",
        "Arancel": 4300000,
        "Matricula": 120000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uahurtado.cl/ciencias-politicas"
    },
    {
        "NombreUniversidad": "Universidad del Pacífico",
        "NombreCarrera": "Publicidad",
        "DescripcionCarrera": "Carrera de publicidad.",
        "SemestresCarrera": 8,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Comunicación",
        "Arancel": 4100000,
        "Matricula": 110000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.upacifico.cl/publicidad"
    },
    {
        "NombreUniversidad": "Universidad de Aconcagua",
        "NombreCarrera": "Trabajo Social",
        "DescripcionCarrera": "Carrera de trabajo social.",
        "SemestresCarrera": 10,
        "RegionCarrera": 6,
        "ComunaCarrera": "San Felipe",
        "AreaEstudio": "Ciencias Sociales",
        "Arancel": 4200000,
        "Matricula": 120000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uaconcagua.cl/trabajo-social"
    },
    {
        "NombreUniversidad": "Universidad Adventista de Chile",
        "NombreCarrera": "Teología",
        "DescripcionCarrera": "Carrera de teología.",
        "SemestresCarrera": 10,
        "RegionCarrera": 16,
        "ComunaCarrera": "Chillán",
        "AreaEstudio": "Humanidades",
        "Arancel": 4000000,
        "Matricula": 100000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.unach.cl/teologia"
    },
    {
        "NombreUniversidad": "Universidad de las Américas",
        "NombreCarrera": "Pedagogía en Historia y Geografía",
        "DescripcionCarrera": "Carrera de pedagogía.",
        "SemestresCarrera": 8,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Educación",
        "Arancel": 4200000,
        "Matricula": 110000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.udla.cl/pedagogia-historia"
    },
    {
        "NombreUniversidad": "Universidad Viña del Mar",
        "NombreCarrera": "Administración Pública",
        "DescripcionCarrera": "Carrera de administración.",
        "SemestresCarrera": 8,
        "RegionCarrera": 5,
        "ComunaCarrera": "Viña del Mar",
        "AreaEstudio": "Administración y Comercio",
        "Arancel": 4300000,
        "Matricula": 120000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.uvm.cl/administracion-publica"
    },
    {
        "NombreUniversidad": "Universidad Chileno-Británica de Cultura",
        "NombreCarrera": "Traducción e Interpretación",
        "DescripcionCarrera": "Carrera de traducción.",
        "SemestresCarrera": 8,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Comunicación",
        "Arancel": 4200000,
        "Matricula": 110000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.ubritanica.cl/traduccion"
    },
    {
        "NombreUniversidad": "Universidad de Ciencias de la Informática",
        "NombreCarrera": "Ingeniería en Informática",
        "DescripcionCarrera": "Carrera de informática.",
        "SemestresCarrera": 8,
        "RegionCarrera": 13,
        "ComunaCarrera": "Santiago",
        "AreaEstudio": "Ingeniería",
        "Arancel": 4500000,
        "Matricula": 130000,
        "Gratuidad": False,
        "Regimen": "Diurno",
        "link": "http://www.ucinf.cl/informatica"
    }
]

def populate_carreras():
    for carrera_data in carreras:
        carrera = Carrera(**carrera_data)
        carrera.save()
    print("Carreras agregadas a la base de datos.")

if __name__ == "__main__":
    populate_carreras()
