# Generated by Django 5.0.3 on 2024-07-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='Arancel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carrera',
            name='AreaEstudio',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrera',
            name='Gratuidad',
            field=models.CharField(default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='carrera',
            name='Matricula',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='Regimen',
            field=models.CharField(default='Diurno', max_length=50),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
