# Generated by Django 5.0.3 on 2024-05-25 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usersession_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
