# Generated by Django 5.0.6 on 2024-07-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrera_arancel_carrera_areaestudio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='Gratuidad',
            field=models.BooleanField(default=False),
        ),
    ]
