# Generated by Django 5.0.6 on 2024-07-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_carrera_gratuidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='imagen_malla',
            field=models.ImageField(blank=True, null=True, upload_to='mallas/'),
        ),
    ]
