# Generated by Django 5.0.6 on 2024-07-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_carrera_imagen_malla'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='linkred',
            field=models.URLField(default=''),
        ),
    ]
