# Generated by Django 5.0.6 on 2024-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carrera_linkred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='linkred',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
